[package]
name = "forge"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name= "forge"

[dependencies]
actix-web = "4.9.0"
reqwest = "0.12.7"
tokio = {version="1.40.0", features=["macros", "rt-multi-thread"]}
