services:
  reverse-proxy:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=sulemanmahmood99@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      # - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  raabta_backend:
    image: forge
    environment:
      APP_ENVIRONMENT: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raabta_backend.rule=Host(`suleman-mahmood.com`)"
      - "traefik.http.services.raabta_backend.loadbalancer.server.port=80"
      - "traefik.http.routers.raabta_backend.entrypoints=websecure"
      - "traefik.http.routers.raabta_backend.tls.certresolver=myresolver"

  raabta_postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raabta
    volumes:
      - raabta_pg_data:/var/lib/postgresql/data

volumes:
  raabta_pg_data:
  letsencrypt:
