version: '1'
services:
  raabta_backend:
    image: forge
    ports:
      - "8000:8000"

  raabta_postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raabta
    ports:
      - "5432:5432"
