services:
  reverse-proxy:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.dbsecure.address=:5432"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.webresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.webresolver.acme.email=sulemanmahmood99@gmail.com"
      - "--certificatesresolvers.webresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.pgresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.pgresolver.acme.email=sulemanmahmood99@gmail.com"
      - "--certificatesresolvers.pgresolver.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "5432:5432"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  raabta_backend:
    image: forge
    environment:
      APP_ENVIRONMENT: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raabta_backend.rule=Host(`suleman.dev`)"
      - "traefik.http.routers.raabta_backend.entrypoints=websecure"
      - "traefik.http.routers.raabta_backend.tls.certresolver=webresolver"
      - "traefik.http.services.raabta_backend.loadbalancer.server.port=80"

  raabta_postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raabta
    volumes:
      - raabta_pg_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.raabta_postgres.rule=HostSNI(`suleman.dev`)"
      - "traefik.tcp.routers.raabta_postgres.entrypoints=dbsecure"
      - "traefik.tcp.routers.raabta_postgres.tls=true"
      - "traefik.tcp.routers.raabta_postgres.tls.certresolver=pgresolver"
      - "traefik.tcp.services.raabta_postgres.loadbalancer.server.port=5432"

volumes:
  raabta_pg_data:
  letsencrypt:
