services:
  reverse-proxy:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  raabta_backend:
    image: forge
    environment:
      APP_ENVIRONMENT: production
    labels:
      - "traefik.http.routers.raabta_backend.rule=Host('195.201.32.108')"

  raabta_postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raabta
    volumes:
      - raabta_pg_data:/var/lib/postgresql/data

volumes:
  raabta_pg_data:
