services:
  raabta_backend:
    image: forge
    ports:
      - "8000:8000"

  raabta_postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raabta
    volumes:
      - raabta_pg_data:/var/lib/postgresql/data

volumes:
  raabta_pg_data:
