services:
  reverse-proxy:
    image: traefik:latest
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.pg.address=:5432"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=sulemanmahmood99@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  raabta_backend:
    image: forge
    environment:
      APP_ENVIRONMENT: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raabta_backend.rule=Host(`suleman.dev`)"
      - "traefik.http.routers.raabta_backend.entrypoints=websecure"
      - "traefik.http.routers.raabta_backend.tls.certresolver=myresolver"
      - "traefik.http.services.raabta_backend.loadbalancer.server.port=80"

  raabta_postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raabta
    volumes:
      - raabta_pg_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.raabta_postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.raabta_postgres.entrypoints=pg"
      - "traefik.tcp.services.raabta_postgres.loadbalancer.server.port=5432"

volumes:
  raabta_pg_data:
  letsencrypt:
