version: '3'

services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--api.insecure=true"                             # Enable the Traefik dashboard (dev mode)
      - "--providers.docker=true"                         # Enable Docker provider
      - "--entrypoints.web.address=:8000"                 # HTTP entrypoint for app traffic
    ports:
      - "8000:8000"                                       # Forward port 8000 for HTTP app traffic
      - "8080:8080"                                       # Web UI port
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  raabta_backend:
    image: forge
    labels:
      - "traefik.http.routers.raabta_backend.rule=Host(`raabta_backend.localhost`)"
      - "traefik.http.services.raabta_backend.loadbalancer.server.port=8000"

  raabta_postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: raabta
    volumes:
      - raabta_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  raabta_pg_data:
